### ISSUE TITLE
Suggestion: Give top module the same name as package name

### ISSUE THREAD

**Issue by Qqwy** [sabiwara/aja#1]
Currently, the library is called `aja` but the main module is called just `A`.

As per Elixir's [library guidelines](https://hexdocs.pm/elixir/1.12/library-guidelines.html#avoid-defining-modules-that-are-not-in-your-namespace), this is a bit of an antipattern.

My suggestion would be to name the main module also `Aja`. 
If people really want to use the shorter name, they can always alias the module in their local code.

What do you think? :slightly_smiling_face:

**Comment by sabiwara** [comment]
This is a very good point, thanks for opening this issue :heart:
I thought this was a bit of a grey area, but I didn't realize it was in violation of the official guidelines.
Luckily `Aja` is already quite short, so it will only add two letters :slightly_smiling_face:
